### ISSUE TITLE
issue launching after pull

### ISSUE THREAD

**Issue by Kiefff** [ilsawa/p2pool-dgb-scrypt#4]
after seeing your update and doing a git pull, im now having this error spammed when trying to run p2pool now.
`--- <exception caught here> ---
  File "/home/skynet/p2pool-dgb-scrypt/p2pool/data.py", line 988, in __init__
    share = load_share(raw_share, self.net, None)
  File "/home/skynet/p2pool-dgb-scrypt/p2pool/data.py", line 57, in load_share
    return NewShare(net, peer_addr, NewShare.share_type.unpack(share['contents']))
  File "/home/skynet/p2pool-dgb-scrypt/p2pool/data.py", line 289, in __init__
    raise p2p.PeerMisbehavingError('share PoW invalid')
p2pool.p2p.PeerMisbehavingError: share PoW invalid

HARMLESS error while reading saved shares, continuing where left off:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/skynet/p2pool-dgb-scrypt/p2pool/main.py", line 180, in main
    ss = p2pool_data.ShareStore(os.path.join(datadir_path, 'shares.'), net, share_cb, known_verified.add)`

**Comment by Kiefff** [comment]
after leaving it running for about 10mins, It finally connected to another peer and everything cleared up. Sorry =X
